cask "agent-vault" do
  version "2026.09.09.234935"
  sha256 "e6dc8325ff1fa0a9335157e89ba8e2a20fcc0d2772c1abfa9a604a95033956cd"

  # Generated by .github/scripts/render-cask.sh — edit that, not this file.
  #
  # The release lives in a PRIVATE repo, so this is the API asset endpoint
  # (addressable only by opaque numeric ID, which is why the URL can't
  # interpolate `version` the way a normal cask does). `browser_download_url`
  # is not usable: it needs a web session, not a token.
  #
  # Homebrew sends these headers to api.github.com, then drops them on the
  # cross-host redirect to release-assets.githubusercontent.com — which is
  # correct, because that URL is already pre-signed.
  url "https://api.github.com/repos/matiasjrossi/agent-vault/releases/assets/553817593",
      header: [
        "Accept: application/octet-stream",
        "Authorization: bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
      ]
  name "Agent Vault"
  desc "Credential broker that injects secrets into agent traffic"
  homepage "https://github.com/matiasjrossi/agent-vault"

  # Releases ship darwin/arm64 only.
  depends_on arch: :arm64

  binary "agent-vault"

  caveats <<~CAVEAT
    agent-vault ships from a private repository, so install and upgrade need a
    GitHub token with read access to matiasjrossi/agent-vault:

      export HOMEBREW_GITHUB_API_TOKEN=<token>

    Without one the download fails as a bare 404 — GitHub reports private
    resources as Not Found rather than Unauthorized.
  CAVEAT
end
