cask "agent-vault" do
  version "0.39.2-cc.1"
  sha256 "35aee2b13dcead01a505f6f293d32f7742b33ff47a8b6627c4a70eb791f23245"

  # Generated by .github/scripts/render-cask.sh — edit that, not this file.
  #
  # The release lives in a PRIVATE repo, so this is the API asset endpoint
  # (addressable only by opaque numeric ID, which is why the URL can't
  # interpolate `version` the way a normal cask does). `browser_download_url`
  # is not usable: it needs a web session, not a token.
  #
  # Homebrew sends these headers to api.github.com, then drops them on the
  # cross-host redirect to release-assets.githubusercontent.com — which is
  # correct, because that URL is already pre-signed.
  url "https://api.github.com/repos/matiasjrossi/agent-vault/releases/assets/549281452",
      header: [
        "Accept: application/octet-stream",
        "Authorization: bearer #{ENV.fetch("HOMEBREW_GITHUB_API_TOKEN", "")}",
      ]
  name "Agent Vault"
  desc "Credential broker that injects secrets into agent traffic"
  homepage "https://github.com/matiasjrossi/agent-vault"

  # Releases ship darwin/arm64 only.
  depends_on arch: :arm64

  binary "agent-vault"

  caveats <<~CAVEAT
    agent-vault ships from a private repository, so install and upgrade need a
    GitHub token with read access to matiasjrossi/agent-vault:

      export HOMEBREW_GITHUB_API_TOKEN=<token>

    Without one the download fails as a bare 404 — GitHub reports private
    resources as Not Found rather than Unauthorized.
  CAVEAT
end
